FROM kaybenleroll/rminions:latest
LABEL maintainer="Mick Cooney <mickcooney@gmail.com>"


ENV REDIS "localhost"
ENV QUEUE "jobsQueue"

RUN apt-get update \
  && apt-get install -y \
    libgsl-dev \
  && rm -rf /var/lib/apt/lists/* \
  && install2.r --error \
    redux \
    tidybayes \
    tidyverse \
    zoo

RUN mkdir -p /R
WORKDIR /R
COPY ./btydbayes /R

RUN r -e 'devtools::install()' \
  && chmod +x /R/runMinion.sh

CMD [ "./runMinion.sh" ]
